### PR TITLE
Move getData api service to repository and do some unit testing in viewModel

### PR DESCRIPTION
**Pull request by aridwiprayogo**

### CODE REVIEW

**Comment by rrifafauzikomara** [comment]
Hallo @aridwiprayogo 

Thank's for the `PR`. I will check later ya :D

**Comment by aridwiprayogo** [comment]
Okey, it just a little bit of testing. After you review this PR if you satisfied, I would probably do testing a whole of feature in this application

**Comment by rrifafauzikomara** [comment]
Hallo mas @aridwiprayogo 

All you add in the `PR` is LGTM, I just comment a naming of versioning dependencies. Can you fix it and also If you want to add more testing as you say before. I will appreciate it.

**Comment by aridwiprayogo** [comment]
Okey I'll check it

**Pull request merged**
